export const AUTH_USER="AUTH_USER";
export const GET_PATIENT_APPOINTMENTS="GET_PATIENT_APPOINTMENTS";
export const GET_APPOINTMENTS="GET_APPOINTMENTS";
export const CANCEL_APPOINTMENT="CANCEL_APPOINTMENT";
export const REMOVE_CURRENT_USER_APPOINTMENT="REMOVE_CURRENT_USER_APPOINTMENT";
export const REMOVE_FILTER_APPOINTMENT="REMOVE_CURRENT_USER_APPOINTMENT";